### PR TITLE
The tools/file2dsk tool needed to build the project.

### PR DESCRIPTION
**Pull request by abcbarryn**
This script uses and depends on the decb command from toolshed at https://sourceforge.net/projects/toolshed/.

### CODE REVIEW

**Comment by richard42** [comment]
Sorry, but this didn't really fix the dependency, by requiring the decb command. I fixed this instead by adding the C source code for the file2dsk utility. Thanks for pointing out the problem.

**Comment by drencorxeen** [comment]
I myself probably would have put int he docs that having the file2dsk utility built and installed from the creators site.

Show people where to get the required utility and then people can follow the creators instructions for building the required utility.

Just like most people who use the Toolshed Project build the project and install it.  Also the same goes for lwtools from LostWizard.  Build and install the required tool package.

Though that is just my opinion. :D

**Comment by richard42** [comment]
Yeah this project is definitely "some assembly required".  I should put the DSK image from the 1.2 release on the release page so people who just want to run the tester can get it here. Probably most people don't want to build this from the source code.

**Comment by drencorxeen** [comment]
@richard42 ,
Yes that would be helpful for sure having the DSK image under the releases. :)

Since I have the all of toolshed and this file2dsk installed in my path on my Linux box.  I just modified the Makefile so it would just use the utilities from the system itself rather than from the tools folder.  That way it was easier for me to just build rather than having 20 copies of the utility floating around in multiple directoroies lol.

**Comment by richard42** [comment]
OK, I made a release and uploaded a ZIP containing the DSK image.  And you actually might want to diff the source code between the toolshed utility file2dsk and my version.  I'm not 100% sure now but I don't think I originally forked this from toolshed. For some reason I seem to remember that I took this from MAME or some other project.  It's been so many years, maybe I'm remembering it wrong. But I do know that I had to modify this program to make it work properly under Linux. There was something wrong with it; I think it had a problem with case-sensitive filesystems.

**Pull request closed without merging**
